[terminal.shell]
program = "wsl.exe"
args = ["~"]

[env]
TERM = "xterm-256color"

[general]
import = ["blue-gold.toml"]

working_directory = "C:/Users/Leo"

[window]
opacity = 0.85
blur = true

padding.x = 0
padding.y = 0
dynamic_padding = false

decorations = "None"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 19
